### ISSUE TITLE
Getting message "Please enable javascript" on login page

### ISSUE THREAD

**Issue by Rubonnek** [YunoHost-Apps/cockpit_ynh#16]
### Describe the bug

Getting message "Please enable javascript" on login page and I'm unable to access the Cockpit UI.

### Context

- Hardware: virtualized through QEMU
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 11.0.9.15
yunohost-admin: 
  repo: stable
  version: 11.0.10
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough:
    ```sh
    sudo yunohost app install cockpit
    ```
- Attempt to access cockpit through URL where it was installed

### Expected behavior

I would be greeted by the login page

### Logs

```
Oct 04 18:40:18 mydomain.tld cockpit-ws[4776]: cockpit-ws: couldn't load configuration file: /etc/cockpit/cockpit.conf: Permission denied
Oct 04 18:45:12 mydomain.tld cockpit-ws[5195]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4>
```

*If applicable and useful, add screenshots to help explain your problem.*

### Possible fix / workaround

I was able to access Cockpit's login page after executing:

sudo chmod +r /etc/cockpit/cockpit.conf
