### ISSUE TITLE
Limited user access

### ISSUE THREAD

**Issue by Rubonnek** [YunoHost-Apps/cockpit_ynh#17]
### Describe the bug

After logging into the cockpit UI, a user will be of limited access if the are not in the `sudo` group.

### Context

- Hardware: virtualized through QEMU
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 11.0.9.15
yunohost-admin: 
  repo: stable
  version: 11.0.10
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install cockpit
    ```
- Apply the workaround on #16 to be able to access the web ui:
    ```bash
    sudo chmod +r /etc/cockpit/cockpit.conf
    ```
- Access Cockpit's web UI through the URL it was installed in.
- Note the "Limited Access" entry in the top right bar. When an user has administrator access, it should read "Administrative access".*

### Expected behavior

I expected to be able to somehow let users escalate privileges through the yunohost UI (i.e. to be able to add them to the `sudo` group through the UI)

There's no documentation either so I'm providing a workaround below.

### Logs

N/A

###  Workaround

Open a terminal in yunohost and add the user to the `sudo` group:

```
sudo gpasswd -a myuser sudo
```
